language: bash

install:
    - PATH=$PWD/bin:$PATH
    - juju -f echo 'Installing juju'
    - sed -i -e "s/#Server/Server/" ~/.juju/etc/pacman.d/mirrorlist
    - juju -f pacman --noconfirm -Syy

script:
# Test on installing package from AUR (issue #58)
    - juju -f pacman --noconfirm -S base-devel --needed
    - juju -f yaourt --noconfirm -S biicode
    - juju bii -v
